name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  16

      - name: Install dependencies
        run: npm install

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Deploy to Railway
        run: railway up --service="RandomEmoji" -- --token="${{ secrets.RAILWAY_TOKEN}}"


